### ISSUE TITLE
Get Utterances comments to be automatically labeled with `website_comments`

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [ElectricRCAircraftGuy/ElectricRCAircraftGuy.github.io#18]
I'm not sure why this isn't working, but figure it out.

https://github.com/ElectricRCAircraftGuy/ElectricRCAircraftGuy.github.io/issues/labels

https://utteranc.es/ --> see "label (optional)" key entry

I have the label set here: https://github.com/ElectricRCAircraftGuy/ElectricRCAircraftGuy.github.io/blob/master/_config.yml#L79

```yaml
  utterances:
    theme                : "github-light" # "github-light" (default), "github-dark"
    issue_term           : "pathname" # "pathname" (default)
    # GS added: "the label that will be assigned to issues created by Utterances." "Label names are
    # case sensitive. The label must exist in your repo- Utterances cannot attach labels that do not
    # exist. Emoji are supported in label names.✨💬✨".
    label                : "website_comments"  # <==========
```
